# Generated by Django 5.0.3 on 2024-06-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mobile_number'),
        ('accounts', '0005_alter_customer_image_name'),
    ]

    operations = [
    ]
