# Generated by Django 5.0.3 on 2026-07-29 03:51

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='register_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='author',
            name='register_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات کامل مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(upload_to='images/blogimg/', verbose_name='تصویر اصلی مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summery_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان مقاله'),
        ),
    ]
