# Generated by Django 5.0.3 on 2024-06-25 18:33

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slider_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image_name',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_title',
            field=models.ImageField(default=1, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
            preserve_default=False,
        ),
    ]
