# Generated by Django 5.0.3 on 2024-06-25 19:57

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_slider_image_name_slider_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_titel1',
            new_name='slider_title1',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_titel2',
            new_name='slider_title2',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_titel3',
            new_name='slider_title3',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
    ]
