# Generated by Django 5.0.3 on 2024-06-27 11:33

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_slider_titel1_slider_slider_title1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
    ]
