# Generated by Django 5.0.3 on 2024-06-28 11:19

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_slider_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
    ]
