# Generated by Django 5.0.3 on 2026-07-21 03:27

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customer_image_name'),
        ('main', '0017_alter_slider_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع  ')),
                ('descriptions', models.TextField(max_length=3000, verbose_name='نظرات  ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_title',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200, verbose_name=' عنوان متن')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=None)),
                ('image_title', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_Customuser', to='accounts.customer', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ماها',
            },
        ),
    ]
